# docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file: ".env"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - mssql-log:/var/opt/mssql/log